[package]
name = "cyber_live_brain"
version = "0.5.5"
edition = "2021"

[dependencies]
tiny_http = "0.12"
tokio = { version = "1", features = ["full"] }
async-openai = "0.26"
dotenvy = "0.15"
cpal = "0.15"
hound = "3.5"
lazy_static = "1.4"
